document.addEventListener("DOMContentLoaded", () => {
  // ========== MOBILE MENU ==========
  const menu = document.querySelector("#mobile-menu");
  const menuLinks = document.querySelector(".nav-links");
  if (menu) {
    menu.addEventListener("click", () => {
      menuLinks.classList.toggle("active");
      menu.classList.toggle("is-active");
    });
  }

  // ========== CLOCKS ==========
  function updateClocks() {
    const now = new Date();
    document.getElementById("local-clock").innerText = now.toLocaleTimeString(
      [],
      { hour: "2-digit", minute: "2-digit", hour12: false },
    );
    const trackTime = new Date(
      now.toLocaleString("en-US", { timeZone: "America/Toronto" }),
    );
    document.getElementById("track-clock").innerText =
      trackTime.toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
        hour12: false,
      });
  }
  setInterval(updateClocks, 1000);
  updateClocks();

  // ========== RACE CALENDAR ==========
  const sb =
    "https://cdn.jsdelivr.net/gh/julesr0y/f1-circuits-svg@main/circuits/minimal/white-outline/";
  const races = [
    {
      round: 1,
      location: "Australia",
      city: "Melbourne",
      flag: "au",
      date: "06 - 08 MAR",
      circuit: "Albert Park Circuit",
      laps: 58,
      length: "5.278 km",
      dist: "306.124 km",
      lapRecord: "1:19.813 (Leclerc, 2024)",
      firstGP: 1996,
      pitLoss: "~21s",
      track: sb + "melbourne-2.svg",
      status: "completed",
      corners: [
        "T1 Jones",
        "T3 Brabham",
        "T6 Whiteford",
        "T9-10 Lakeside",
        "T11 Ascari",
        "T12 Stewart",
        "T13 Senna",
        "T14 Prost",
      ],
      results: [
        { pos: "1st", d: "Russell", c: "RUS", t: "1:23:06.801" },
        { pos: "2nd", d: "Antonelli", c: "ANT", t: "+2.974" },
        { pos: "3rd", d: "Leclerc", c: "LEC", t: "+15.519" },
      ],
    },
    {
      round: 2,
      location: "China",
      city: "Shanghai",
      flag: "cn",
      date: "13 - 15 MAR",
      circuit: "Shanghai International Circuit",
      laps: 56,
      length: "5.451 km",
      dist: "305.066 km",
      lapRecord: "1:32.238 (M. Schumacher, 2004)",
      firstGP: 2004,
      pitLoss: "~24s",
      track: sb + "shanghai-1.svg",
      status: "completed",
      corners: [
        "T1-3 Turns Complex",
        "T6 Hairpin",
        "T7-8 Esses",
        "T11 Back Hairpin",
        "T13 Shanghai Corner",
        "T14-15 Last Chicane",
      ],
      results: [
        { pos: "1st", d: "Antonelli", c: "ANT", t: "1:33:15.607" },
        { pos: "2nd", d: "Russell", c: "RUS", t: "+5.515" },
        { pos: "3rd", d: "Hamilton", c: "HAM", t: "+25.267" },
      ],
    },
    {
      round: 3,
      location: "Japan",
      city: "Suzuka",
      flag: "jp",
      date: "27 - 29 MAR",
      circuit: "Suzuka International Racing Course",
      laps: 53,
      length: "5.807 km",
      dist: "307.471 km",
      lapRecord: "1:30.965 (Antonelli, 2025)",
      firstGP: 1987,
      pitLoss: "~22s",
      track: sb + "suzuka-1.svg",
      status: "completed",
      corners: [
        "T1-2 First Curve",
        "T3-6 Esses",
        "T7 Dunlop",
        "T8-9 Degner 1 & 2",
        "T11 Hairpin",
        "T13 Spoon",
        "T15 130R",
        "T16-17 Casio Chicane",
      ],
      results: [
        { pos: "1st", d: "Antonelli", c: "ANT", t: "1:28:03.403" },
        { pos: "2nd", d: "Piastri", c: "PIA", t: "+13.722" },
        { pos: "3rd", d: "Leclerc", c: "LEC", t: "+15.270" },
      ],
    },
    {
      round: 4,
      location: "Miami",
      city: "Miami",
      flag: "us",
      date: "01 - 03 MAY",
      circuit: "Miami International Autodrome",
      laps: 57,
      length: "5.412 km",
      dist: "308.326 km",
      lapRecord: "1:29.708 (Verstappen, 2023)",
      firstGP: 2022,
      pitLoss: "~24s",
      track: sb + "miami-1.svg",
      status: "completed",
      corners: [
        "T1 Braking Zone",
        "T4-5 Chicane",
        "T7 Hairpin",
        "T11 Hard Rock Turn",
        "T14-16 Stadium Section",
        "T17 Final Corner",
      ],
      results: [
        { pos: "1st", d: "Antonelli", c: "ANT", t: "1:33:19.273" },
        { pos: "2nd", d: "Norris", c: "NOR", t: "+3.264" },
        { pos: "3rd", d: "Piastri", c: "PIA", t: "+27.092" },
      ],
    },
    {
      round: 5,
      location: "Canada",
      city: "Montreal",
      flag: "ca",
      date: "22 - 24 MAY",
      circuit: "Circuit Gilles Villeneuve",
      laps: 70,
      length: "4.361 km",
      dist: "305.270 km",
      lapRecord: "1:13.078 (Bottas, 2019)",
      firstGP: 1978,
      pitLoss: "~21s",
      track: sb + "montreal-2.svg",
      status: "completed",
      corners: [
        "T1-2 Senna Esses",
        "T3 Island Hairpin",
        "T6 Viking Corner",
        "T8-9 L'\u00c9pingle (Hairpin)",
        "T10 Backstraight Kink",
        "T13 Wall of Champions",
      ],
      results: [
        { pos: "1st", d: "Antonelli", c: "ANT", t: "1:28:15.758" },
        { pos: "2nd", d: "Hamilton", c: "HAM", t: "+10.768s" },
        { pos: "3rd", d: "Verstappen", c: "VER", t: "+11.276s" },
      ],
    },
    {
      round: 6,
      location: "Monaco",
      city: "Monte Carlo",
      flag: "mc",
      date: "05 - 07 JUN",
      circuit: "Circuit de Monaco",
      laps: 78,
      length: "3.337 km",
      dist: "260.286 km",
      lapRecord: "1:12.909 (Hamilton, 2021)",
      firstGP: 1950,
      pitLoss: "~24s",
      track: sb + "monaco-3.svg",
      status: "next",
      corners: [
        "T1 Sainte D\u00e9vote",
        "T3 Beau Rivage Hill",
        "T5 Casino Square",
        "T6 Grand H\u00f4tel Hairpin",
        "T8 Portier",
        "Tunnel",
        "T10 Chicane",
        "T12-13 Swimming Pool",
        "T17 Rascasse",
        "T18 Anthony Nogh\u00e8s",
      ],
    },
    {
      round: 7,
      location: "Barcelona-Catalunya",
      city: "Barcelona",
      flag: "es",
      date: "12 - 14 JUN",
      circuit: "Circuit de Barcelona-Catalunya",
      laps: 66,
      length: "4.657 km",
      dist: "307.236 km",
      lapRecord: "1:16.330 (Piastri, 2025)",
      firstGP: 1991,
      pitLoss: "~22s",
      track: sb + "catalunya-6.svg",
      status: "upcoming",
      corners: [
        "T1 Elf",
        "T2 Renault",
        "T3 Repsol",
        "T4 Seat",
        "T5 Campsa",
        "T7 Wurth",
        "T9 Banc de Sabadell",
        "T10 La Caixa",
        "T14-15 New Chicane",
        "T16 New Final Corner",
      ],
    },
    {
      round: 8,
      location: "Austria",
      city: "Spielberg",
      flag: "at",
      date: "26 - 28 JUN",
      circuit: "Red Bull Ring",
      laps: 71,
      length: "4.318 km",
      dist: "306.452 km",
      lapRecord: "1:05.619 (Sainz, 2020)",
      firstGP: 1970,
      pitLoss: "~21s",
      track: sb + "spielberg-3.svg",
      status: "upcoming",
      corners: [
        "T1 Niki Lauda Kurve",
        "T2 Remus",
        "T3 Schlossgold Kurve",
        "T4 Rauch Kurve",
        "T6 Rindt Kurve",
        "T7 W\u00fcrth Kurve",
        "T8 A1 Kurve",
        "T9 Jochen Rindt Chicane",
        "T10 Red Bull Mobile Kurve",
      ],
    },
    {
      round: 9,
      location: "Great Britain",
      city: "Silverstone",
      flag: "gb",
      date: "03 - 05 JUL",
      circuit: "Silverstone Circuit",
      laps: 52,
      length: "5.891 km",
      dist: "306.198 km",
      lapRecord: "1:27.097 (Verstappen, 2020)",
      firstGP: 1950,
      pitLoss: "~22s",
      track: sb + "silverstone-6.svg",
      status: "upcoming",
      corners: [
        "T1 Abbey",
        "T3 Village",
        "T4 The Loop",
        "T6 Brooklands",
        "T7 Luffield",
        "T9 Copse",
        "T11-13 Maggots, Becketts & Chapel",
        "T14 Stowe",
        "T15 Vale",
        "T16 Club",
      ],
    },
    {
      round: 10,
      location: "Belgium",
      city: "Spa-Francorchamps",
      flag: "be",
      date: "17 - 19 JUL",
      circuit: "Circuit de Spa-Francorchamps",
      laps: 44,
      length: "7.004 km",
      dist: "308.052 km",
      lapRecord: "1:44.701 (P\u00e9rez, 2024)",
      firstGP: 1950,
      pitLoss: "~22s",
      track: sb + "spa-francorchamps-3.svg",
      status: "upcoming",
      corners: [
        "T1 La Source",
        "T3-4 Eau Rouge & Raidillon",
        "Kemmel Straight",
        "T7 Les Combes",
        "T8 Malmedy",
        "T10 Pouhon",
        "T12-13 Fagnes Chicane",
        "T15 Blanchimont",
        "T18-19 Bus Stop Chicane",
      ],
    },
    {
      round: 11,
      location: "Hungary",
      city: "Budapest",
      flag: "hu",
      date: "24 - 26 JUL",
      circuit: "Hungaroring",
      laps: 70,
      length: "4.381 km",
      dist: "306.630 km",
      lapRecord: "1:16.627 (Hamilton, 2020)",
      firstGP: 1986,
      pitLoss: "~22s",
      track: sb + "hungaroring-2.svg",
      status: "upcoming",
      corners: [
        "T1 Start/Finish Hairpin",
        "T2-3 Hill Esses",
        "T4 Downhill Right",
        "T6 Big Left",
        "T11 Uphill S-curves",
        "T12-13 Chicane",
        "T14 Final Corner",
      ],
    },
    {
      round: 12,
      location: "Netherlands",
      city: "Zandvoort",
      flag: "nl",
      date: "21 - 23 AUG",
      circuit: "Circuit Zandvoort",
      laps: 72,
      length: "4.259 km",
      dist: "306.587 km",
      lapRecord: "1:11.097 (Hamilton, 2021)",
      firstGP: 1952,
      pitLoss: "~20s",
      track: sb + "zandvoort-3.svg",
      status: "upcoming",
      corners: [
        "T1 Tarzanbocht",
        "T2-3 Gerlachbocht",
        "T7 Scheivlak",
        "T8 Mastersbocht",
        "T9 Hans Ernstbocht",
        "T11 Hugenholtz",
        "T12 Kumho",
        "T13 Arie Luyendykbocht",
        "T14 Banked Final Turn",
      ],
    },
    {
      round: 13,
      location: "Italy",
      city: "Monza",
      flag: "it",
      date: "04 - 06 SEP",
      circuit: "Autodromo Nazionale Monza",
      laps: 53,
      length: "5.793 km",
      dist: "306.720 km",
      lapRecord: "1:20.901 (Norris, 2025)",
      firstGP: 1950,
      pitLoss: "~25s",
      track: sb + "monza-2.svg",
      status: "upcoming",
      corners: [
        "T1-2 Variante del Rettifilo",
        "T4-5 Curva Grande",
        "T6-7 Variante della Roggia",
        "T8-9 Lesmo 1 & 2",
        "T11 Ascari Chicane",
        "Curva Parabolica (Alboreto)",
      ],
    },
    {
      round: 14,
      location: "Spain",
      city: "Madrid",
      flag: "es",
      date: "11 - 13 SEP",
      circuit: "Madrid Circuit",
      laps: 0,
      length: "TBC",
      dist: "TBC",
      lapRecord: "New circuit",
      firstGP: 2026,
      pitLoss: "TBC",
      track: sb + "madring-1.svg",
      status: "upcoming",
      corners: ["New circuit \u2014 corner names TBC"],
    },
    {
      round: 15,
      location: "Azerbaijan",
      city: "Baku",
      flag: "az",
      date: "24 - 26 SEP",
      circuit: "Baku City Circuit",
      laps: 51,
      length: "6.003 km",
      dist: "306.049 km",
      lapRecord: "1:43.009 (Leclerc, 2019)",
      firstGP: 2016,
      pitLoss: "~25s",
      track: sb + "baku-1.svg",
      status: "upcoming",
      corners: [
        "T1-2 Start Complex",
        "T3 Uphill Left",
        "T7 Icheri Sheher (Old City)",
        "T8 Castle Section",
        "T12-13 Inner City Hairpins",
        "T15 Turn into Main Straight",
        "T16 Azeri Corner",
        "T20 Final Corner",
      ],
    },
    {
      round: 16,
      location: "Singapore",
      city: "Singapore",
      flag: "sg",
      date: "09 - 11 OCT",
      circuit: "Marina Bay Street Circuit",
      laps: 62,
      length: "4.940 km",
      dist: "306.143 km",
      lapRecord: "1:33.808 (Hamilton, 2025)",
      firstGP: 2008,
      pitLoss: "~28s",
      track: sb + "marina-bay-4.svg",
      status: "upcoming",
      corners: [
        "T1 Sheares",
        "T5 Stamford",
        "T7 Raffles Blvd Hairpin",
        "T9 War Memorial",
        "T10 Singapore Sling",
        "T13 Esplanade Curve",
        "T14 Turn 14 Chicane",
        "T16-17 Anderson Bridge",
        "T19 Empress Place",
        "T23 Last Corner",
      ],
    },
    {
      round: 17,
      location: "United States",
      city: "Austin",
      flag: "us",
      date: "23 - 25 OCT",
      circuit: "Circuit of the Americas",
      laps: 56,
      length: "5.513 km",
      dist: "308.405 km",
      lapRecord: "1:36.169 (Leclerc, 2019)",
      firstGP: 2012,
      pitLoss: "~22s",
      track: sb + "austin-1.svg",
      status: "upcoming",
      corners: [
        "T1 Uphill Braking Zone",
        "T2-6 Esses Complex",
        "T11 Hairpin",
        "T12 Downhill Switchback",
        "T15 Stadium Turn",
        "T16-18 Stadium Section",
        "T19 Back Straight Kink",
        "T20 Hairpin",
      ],
    },
    {
      round: 18,
      location: "Mexico",
      city: "Mexico City",
      flag: "mx",
      date: "30 OCT - 01 NOV",
      circuit: "Aut\u00f3dromo Hermanos Rodr\u00edguez",
      laps: 71,
      length: "4.304 km",
      dist: "305.354 km",
      lapRecord: "1:17.774 (Bottas, 2021)",
      firstGP: 1963,
      pitLoss: "~22s",
      track: sb + "mexico-city-3.svg",
      status: "upcoming",
      corners: [
        "T1-3 Esses",
        "T4 Main Straight Entry",
        "T6 Horquilla (Hairpin)",
        "T7-9 Mitsubishi Esses",
        "T12 Baseball Diamond",
        "T13-16 Foro Sol Stadium Section",
        "T17 Last Corner",
      ],
    },
    {
      round: 19,
      location: "Brazil",
      city: "S\u00e3o Paulo",
      flag: "br",
      date: "06 - 08 NOV",
      circuit: "Aut\u00f3dromo Jos\u00e9 Carlos Pace",
      laps: 71,
      length: "4.309 km",
      dist: "305.879 km",
      lapRecord: "1:10.540 (Bottas, 2018)",
      firstGP: 1973,
      pitLoss: "~22s",
      track: sb + "interlagos-2.svg",
      status: "upcoming",
      corners: [
        "T1 Senna S",
        "T3 Curva do Sol",
        "T4 Descida do Lago",
        "T6-7 Ferradura",
        "T8 Laranjinha",
        "T10 Pinheirinho",
        "T12 Jun\u00e7\u00e3o",
        "T14 Subida dos Boxes",
      ],
    },
    {
      round: 20,
      location: "Las Vegas",
      city: "Las Vegas",
      flag: "us",
      date: "19 - 21 NOV",
      circuit: "Las Vegas Strip Circuit",
      laps: 50,
      length: "6.201 km",
      dist: "310.050 km",
      lapRecord: "1:33.365 (Verstappen, 2025)",
      firstGP: 2023,
      pitLoss: "~26s",
      track: sb + "las-vegas-1.svg",
      status: "upcoming",
      corners: [
        "T1-2 MSS Chicane",
        "T4 Harmon Corner",
        "T5-6 Koval Chicane",
        "T10 Sands Hairpin",
        "T12 Sphere Turn",
        "T14 Las Vegas Blvd Turn",
        "T17 Final Corner (Strip)",
      ],
    },
    {
      round: 21,
      location: "Qatar",
      city: "Lusail",
      flag: "qa",
      date: "27 - 29 NOV",
      circuit: "Lusail International Circuit",
      laps: 57,
      length: "5.419 km",
      dist: "308.611 km",
      lapRecord: "1:22.384 (Norris, 2024)",
      firstGP: 2021,
      pitLoss: "~23s",
      track: sb + "lusail-1.svg",
      status: "upcoming",
      corners: [
        "T1 Start Corner",
        "T4-5 Esses",
        "T6 Fast Left",
        "T7 Switchback Right",
        "T10 Hairpin",
        "T12-13 Double Apex",
        "T14 Fast Right",
        "T16 Penultimate Corner",
      ],
    },
    {
      round: 22,
      location: "Abu Dhabi",
      city: "Abu Dhabi",
      flag: "ae",
      date: "04 - 06 DEC",
      circuit: "Yas Marina Circuit",
      laps: 58,
      length: "5.281 km",
      dist: "306.183 km",
      lapRecord: "1:25.637 (Magnussen, 2024)",
      firstGP: 2009,
      pitLoss: "~23s",
      track: sb + "yas-marina-2.svg",
      status: "upcoming",
      corners: [
        "T1-2 Turn 1 Complex",
        "T5 Hotel Hairpin",
        "T6-7 North Esses",
        "T9 Hotel Chicane",
        "T11 Marina Hairpin",
        "T12-14 South Marina Esses",
        "T16 Yas Chicane",
        "T17-18 North Chicane",
      ],
    },
  ];

  const container = document.getElementById("circuits-list");
  races.forEach((r, i) => {
    const card = document.createElement("div");
    card.className =
      "circuit-card" +
      (r.status === "completed" ? " circuit-completed" : "") +
      (r.status === "next" ? " circuit-next" : "");
    card.style.animationDelay = i * 0.06 + "s";
    let badge = "";
    if (r.status === "completed")
      badge =
        '<span class="circuit-badge circuit-badge-done">\u2713 COMPLETED</span>';
    else if (r.status === "next")
      badge =
        '<span class="circuit-badge circuit-badge-next">\u25cf NEXT RACE</span>';
    let res = "";
    if (r.results) {
      res =
        '<div class="circuit-results">' +
        r.results
          .map(function (x, j) {
            return (
              '<div class="circuit-result-row"><span class="result-pos result-pos-' +
              (j + 1) +
              '">' +
              x.pos +
              '</span><span class="result-driver">' +
              x.d +
              " <small>" +
              x.c +
              '</small></span><span class="result-time">' +
              x.t +
              "</span></div>"
            );
          })
          .join("") +
        "</div>";
    }
    var cornerTags = r.corners
      .map(function (c) {
        return '<span class="corner-tag">' + c + "</span>";
      })
      .join("");
    card.innerHTML =
      '<div class="circuit-card-main">' +
      '<div class="circuit-card-left">' +
      '<div class="circuit-round">R' +
      String(r.round).padStart(2, "0") +
      "</div>" +
      '<div class="circuit-track-img"><img src="' +
      r.track +
      '" alt="' +
      r.circuit +
      ' layout" onerror="this.style.display=\'none\'"></div>' +
      '<div class="circuit-info">' +
      '<div class="circuit-location-row"><img src="https://flagcdn.com/w20/' +
      r.flag +
      '.png" alt="' +
      r.location +
      '" class="circuit-flag"><span class="circuit-location">' +
      r.location +
      "</span>" +
      badge +
      "</div>" +
      '<span class="circuit-name">' +
      r.circuit +
      "</span>" +
      '<span class="circuit-date">' +
      r.date +
      "</span>" +
      "</div>" +
      "</div>" +
      '<div class="circuit-card-right">' +
      res +
      "</div>" +
      "</div>" +
      '<div class="circuit-card-details">' +
      '<div class="circuit-detail-grid">' +
      '<div class="detail-cell"><span class="detail-label">Circuit</span><span class="detail-val">' +
      r.circuit +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">First GP</span><span class="detail-val">' +
      r.firstGP +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">Laps</span><span class="detail-val">' +
      (r.laps || "TBC") +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">Circuit Length</span><span class="detail-val">' +
      r.length +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">Race Distance</span><span class="detail-val">' +
      r.dist +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">Lap Record</span><span class="detail-val">' +
      r.lapRecord +
      "</span></div>" +
      '<div class="detail-cell"><span class="detail-label">Pit Stop Loss</span><span class="detail-val">' +
      r.pitLoss +
      "</span></div>" +
      "</div>" +
      '<div class="corners-section">' +
      '<button class="corners-btn" onclick="event.stopPropagation(); this.parentElement.classList.toggle(\'corners-open\')">\ud83c\udfc1 Corner Names <span class="corners-arrow">\u25bc</span></button>' +
      '<div class="corners-list">' +
      cornerTags +
      "</div>" +
      "</div>" +
      "</div>";
    card.addEventListener("click", function () {
      var wasOpen = card.classList.contains("circuit-card-expanded");
      document.querySelectorAll(".circuit-card").forEach(function (c) {
        c.classList.remove("circuit-card-expanded");
      });
      if (!wasOpen) card.classList.add("circuit-card-expanded");
    });
    container.appendChild(card);
  });

  // ========== CIRCUIT EXPLORER ==========
  var tb =
    "https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026track";
  var explorerCircuits = [
    {
      id: "melbourne",
      name: "Albert Park Circuit",
      location: "Melbourne, Australia",
      flag: "au",
      length: "5.278 km",
      laps: 58,
      firstGP: 1996,
      lapRecord: "1:19.813 (Leclerc, 2024)",
      trackSvg: tb + "melbournedetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight after T14" }],
      corners: [
        {
          num: 1,
          name: "Jones",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Chicane",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Brabham",
          type: "Medium Speed",
          speed: "120 km/h",
          gear: 3,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Fast Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Fast Left",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Whiteford",
          type: "Fast Right",
          speed: "185 km/h",
          gear: 6,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Medium Right",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Lakeside",
          type: "Medium Left",
          speed: "110 km/h",
          gear: 3,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 11,
          name: "Ascari",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 12,
          name: "Stewart",
          type: "Tight Chicane",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 13,
          name: "Senna",
          type: "Medium Speed",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Prost",
          type: "Fast Right",
          speed: "160 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "shanghai",
      name: "Shanghai International Circuit",
      location: "Shanghai, China",
      flag: "cn",
      length: "5.451 km",
      laps: 56,
      firstGP: 2004,
      lapRecord: "1:32.238 (M. Schumacher, 2004)",
      trackSvg: tb + "shanghaidetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight after T16" }],
      corners: [
        {
          num: 1,
          name: "Turns 1-2",
          type: "Tightening Spiral",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Turn 3",
          type: "Spiral Exit",
          speed: "110 km/h",
          gear: 3,
        },
        {
          num: 3,
          name: "Turn 4",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 5",
          type: "Short Straight",
          speed: "235 km/h",
          gear: 6,
        },
        { num: 5, name: "Turn 6", type: "Hairpin", speed: "65 km/h", gear: 2 },
        {
          num: 6,
          name: "Turn 7",
          type: "Esses Entry",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Turn 8",
          type: "Esses Exit",
          speed: "180 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "Turn 9",
          type: "Fast Right",
          speed: "210 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Turn 10",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 10,
          name: "Turn 11",
          type: "Back Hairpin",
          speed: "70 km/h",
          gear: 2,
        },
        {
          num: 11,
          name: "Turn 12",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 12,
          name: "Turn 13",
          type: "Shanghai Corner",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 13,
          name: "Turn 14",
          type: "Chicane Entry",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 14,
          name: "Turn 15",
          type: "Chicane Exit",
          speed: "120 km/h",
          gear: 4,
        },
        {
          num: 15,
          name: "Turn 16",
          type: "Final Corner",
          speed: "155 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "suzuka",
      name: "Suzuka International Racing Course",
      location: "Suzuka, Japan",
      flag: "jp",
      length: "5.807 km",
      laps: 53,
      firstGP: 1987,
      lapRecord: "1:30.965 (Antonelli, 2025)",
      trackSvg: tb + "suzukadetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Start/Finish Straight after T16" }],
      corners: [
        {
          num: 1,
          name: "First Curve",
          type: "Fast Entry",
          speed: "215 km/h",
          gear: 6,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "S Curve 1",
          type: "Esses Entry",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "S Curve 2",
          type: "Esses Middle",
          speed: "165 km/h",
          gear: 4,
        },
        {
          num: 5,
          name: "S Curve 3",
          type: "Esses Exit",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "S Curve 4",
          type: "Fast Flick",
          speed: "178 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Dunlop",
          type: "Blind Crest",
          speed: "245 km/h",
          gear: 7,
        },
        {
          num: 8,
          name: "Degner 1",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 9,
          name: "Degner 2",
          type: "Tight Exit",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 10,
          name: "Underpass",
          type: "Full Throttle",
          speed: "275 km/h",
          gear: 7,
        },
        {
          num: 11,
          name: "Hairpin",
          type: "Heavy Braking",
          speed: "62 km/h",
          gear: 2,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Acceleration",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 13,
          name: "Spoon Entry",
          type: "Long Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Spoon Exit",
          type: "Full Throttle",
          speed: "225 km/h",
          gear: 6,
        },
        {
          num: 15,
          name: "130R",
          type: "Legendary Fast",
          speed: "305 km/h",
          gear: 8,
        },
        {
          num: 16,
          name: "Casio Triangle 1",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 2,
        },
        {
          num: 17,
          name: "Casio Triangle 2",
          type: "Chicane Exit",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 18,
          name: "Final Corner",
          type: "Exit Speed",
          speed: "165 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "miami",
      name: "Miami International Autodrome",
      location: "Miami, United States",
      flag: "us",
      length: "5.412 km",
      laps: 57,
      firstGP: 2022,
      lapRecord: "1:29.708 (Verstappen, 2023)",
      trackSvg: tb + "miamidetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight after T17" }],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Left",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Chicane Entry",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Chicane Exit",
          speed: "120 km/h",
          gear: 4,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Fast Right",
          speed: "190 km/h",
          gear: 5,
        },
        { num: 7, name: "Turn 7", type: "Hairpin", speed: "65 km/h", gear: 2 },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Left",
          speed: "200 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 11,
          name: "Hard Rock Turn",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Medium Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Fast Left",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Stadium Entry",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Stadium Section",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Stadium Exit",
          speed: "150 km/h",
          gear: 5,
        },
        {
          num: 17,
          name: "Turn 17",
          type: "Final Corner",
          speed: "160 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "montreal",
      name: "Circuit Gilles Villeneuve",
      location: "Montreal, Canada",
      flag: "ca",
      length: "4.361 km",
      laps: 70,
      firstGP: 1978,
      lapRecord: "1:13.078 (Bottas, 2019)",
      trackSvg:
        "https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmontrealdetailed.webp?v=2026",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight after T14" }],
      corners: [
        {
          num: 1,
          name: "Senna S (Entry)",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Senna S (Exit)",
          type: "Chicane Exit",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Island Hairpin",
          type: "Hairpin",
          speed: "60 km/h",
          gear: 2,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Fast Right",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Viking Corner",
          type: "Medium Right",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Fast Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "L'\u00c9pingle Entry",
          type: "Heavy Braking",
          speed: "70 km/h",
          gear: 2,
        },
        {
          num: 9,
          name: "L'\u00c9pingle",
          type: "Hairpin",
          speed: "58 km/h",
          gear: 2,
        },
        {
          num: 10,
          name: "Backstraight Kink",
          type: "Flat Out",
          speed: "295 km/h",
          gear: 8,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Fast Right",
          speed: "215 km/h",
          gear: 6,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Chicane Entry",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 13,
          name: "Wall of Champions",
          type: "Final Chicane",
          speed: "115 km/h",
          gear: 3,
        },
      ],
    },
    {
      id: "monaco",
      name: "Circuit de Monaco",
      location: "Monte Carlo, Monaco",
      flag: "mc",
      length: "3.337 km",
      laps: 78,
      firstGP: 1950,
      lapRecord: "1:12.909 (Hamilton, 2021)",
      trackSvg: tb + "montecarlodetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        {
          zone: 1,
          straight: "Start/Finish Straight",
          after: "Anthony Nogh\u00e8s",
        },
      ],
      corners: [
        {
          num: 1,
          name: "Sainte D\u00e9vote",
          type: "Heavy Braking",
          speed: "65 km/h",
          gear: 1,
        },
        {
          num: 2,
          name: "Beau Rivage",
          type: "Uphill Left",
          speed: "120 km/h",
          gear: 3,
        },
        {
          num: 3,
          name: "Massenet",
          type: "Fast Right",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 4,
          name: "Casino",
          type: "Hairpin Entry",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 5,
          name: "Casino Square",
          type: "Tight Right",
          speed: "55 km/h",
          gear: 1,
        },
        {
          num: 6,
          name: "Grand H\u00f4tel Hairpin",
          type: "Slowest Corner",
          speed: "48 km/h",
          gear: 1,
        },
        {
          num: 7,
          name: "Mirabeau",
          type: "Downhill Left",
          speed: "85 km/h",
          gear: 2,
        },
        {
          num: 8,
          name: "Portier",
          type: "Tight Right",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 9,
          name: "Tunnel Entry",
          type: "Fast Kink",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Nouvelle Chicane",
          type: "Chicane",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 11,
          name: "Tabac",
          type: "Fast Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 12,
          name: "Swimming Pool 1",
          type: "Fast Chicane",
          speed: "130 km/h",
          gear: 3,
        },
        {
          num: 13,
          name: "Swimming Pool 2",
          type: "Fast Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "La Rascasse",
          type: "Hairpin",
          speed: "52 km/h",
          gear: 1,
        },
        {
          num: 15,
          name: "Anthony Nogh\u00e8s",
          type: "Final Corner",
          speed: "75 km/h",
          gear: 2,
        },
      ],
    },
    {
      id: "catalunya",
      name: "Circuit de Barcelona-Catalunya",
      location: "Barcelona, Spain",
      flag: "es",
      length: "4.657 km",
      laps: 66,
      firstGP: 1991,
      lapRecord: "1:16.330 (Piastri, 2025)",
      trackSvg: tb + "catalunyadetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T16" },
        { zone: 2, straight: "Back Straight", after: "T9" },
      ],
      corners: [
        {
          num: 1,
          name: "Elf",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Renault",
          type: "Fast Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "Repsol",
          type: "Medium Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 4,
          name: "Seat",
          type: "Medium Left",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 5,
          name: "Campsa",
          type: "Fast Right",
          speed: "210 km/h",
          gear: 6,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Wurth",
          type: "Medium Right",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Kink",
          speed: "220 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Banc de Sabadell",
          type: "Fast Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "La Caixa",
          type: "Heavy Braking",
          speed: "78 km/h",
          gear: 2,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Medium Right",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Fast Left",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Medium Right",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "New Chicane Entry",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 15,
          name: "New Chicane Exit",
          type: "Chicane Exit",
          speed: "110 km/h",
          gear: 3,
        },
        {
          num: 16,
          name: "New Final Corner",
          type: "Medium Right",
          speed: "155 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "spielberg",
      name: "Red Bull Ring",
      location: "Spielberg, Austria",
      flag: "at",
      length: "4.318 km",
      laps: 71,
      firstGP: 1970,
      lapRecord: "1:05.619 (Sainz, 2020)",
      trackSvg: tb + "spielbergdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T10" },
        { zone: 2, straight: "Uphill to T3", after: "T2" },
      ],
      corners: [
        {
          num: 1,
          name: "Niki Lauda Kurve",
          type: "Heavy Braking",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Remus",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Schlossgold Kurve",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 4,
          name: "Rauch Kurve",
          type: "Fast Right",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Fast Kink",
          speed: "245 km/h",
          gear: 7,
        },
        {
          num: 6,
          name: "Rindt Kurve",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 7,
          name: "W\u00fcrth Kurve",
          type: "Fast Right",
          speed: "180 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "A1 Kurve",
          type: "Fast Left",
          speed: "200 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Jochen Rindt Chicane",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 10,
          name: "Red Bull Mobile Kurve",
          type: "Final Corner",
          speed: "145 km/h",
          gear: 4,
        },
      ],
    },
    {
      id: "silverstone",
      name: "Silverstone Circuit",
      location: "Silverstone, United Kingdom",
      flag: "gb",
      length: "5.891 km",
      laps: 52,
      firstGP: 1950,
      lapRecord: "1:27.097 (Verstappen, 2020)",
      trackSvg: tb + "silverstonedetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Wellington Straight", after: "Brooklands" },
        { zone: 2, straight: "Hangar Straight", after: "Chapel" },
      ],
      corners: [
        {
          num: 1,
          name: "Abbey",
          type: "Fast Entry",
          speed: "195 km/h",
          gear: 5,
        },
        { num: 2, name: "Farm", type: "Flat Out", speed: "280 km/h", gear: 7 },
        {
          num: 3,
          name: "Village",
          type: "Heavy Braking",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 4,
          name: "The Loop",
          type: "Hairpin",
          speed: "85 km/h",
          gear: 2,
        },
        {
          num: 5,
          name: "Aintree",
          type: "Fast Exit",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Brooklands",
          type: "Heavy Braking",
          speed: "92 km/h",
          gear: 3,
        },
        {
          num: 7,
          name: "Luffield",
          type: "Long Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 8,
          name: "Woodcote",
          type: "Fast Right",
          speed: "245 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Copse",
          type: "High Speed",
          speed: "285 km/h",
          gear: 8,
        },
        {
          num: 10,
          name: "Maggotts",
          type: "Flat Left",
          speed: "295 km/h",
          gear: 7,
        },
        {
          num: 11,
          name: "Becketts",
          type: "Fast Esses",
          speed: "260 km/h",
          gear: 6,
        },
        {
          num: 12,
          name: "Chapel",
          type: "Flat Out",
          speed: "305 km/h",
          gear: 8,
        },
        {
          num: 13,
          name: "Hangar Straight",
          type: "Full Throttle",
          speed: "325 km/h",
          gear: 8,
        },
        {
          num: 14,
          name: "Stowe",
          type: "Heavy Braking",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 15,
          name: "Vale",
          type: "Chicane Entry",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 16,
          name: "Club",
          type: "Double Right",
          speed: "165 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "spa",
      name: "Circuit de Spa-Francorchamps",
      location: "Spa, Belgium",
      flag: "be",
      length: "7.004 km",
      laps: 44,
      firstGP: 1950,
      lapRecord: "1:44.701 (P\u00e9rez, 2024)",
      trackSvg: tb + "spafrancorchampsdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Kemmel Straight", after: "Raidillon" },
        { zone: 2, straight: "Start/Finish Straight", after: "Bus Stop" },
      ],
      corners: [
        {
          num: 1,
          name: "La Source",
          type: "Hairpin",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Eau Rouge",
          type: "Legendary Corner",
          speed: "290 km/h",
          gear: 7,
        },
        {
          num: 3,
          name: "Raidillon",
          type: "Uphill Crest",
          speed: "305 km/h",
          gear: 8,
        },
        {
          num: 4,
          name: "Les Combes",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 5,
          name: "Malmedy",
          type: "Downhill Left",
          speed: "125 km/h",
          gear: 4,
        },
        { num: 6, name: "Rivage", type: "Hairpin", speed: "80 km/h", gear: 2 },
        {
          num: 7,
          name: "Pouhon",
          type: "Double Apex",
          speed: "255 km/h",
          gear: 7,
        },
        { num: 8, name: "Fagnes", type: "Chicane", speed: "110 km/h", gear: 3 },
        {
          num: 9,
          name: "Stavelot",
          type: "Fast Double",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Blanchimont",
          type: "Flat Out",
          speed: "310 km/h",
          gear: 8,
        },
        {
          num: 11,
          name: "Bus Stop Chicane",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
      ],
    },
    {
      id: "hungaroring",
      name: "Hungaroring",
      location: "Budapest, Hungary",
      flag: "hu",
      length: "4.381 km",
      laps: 70,
      firstGP: 1986,
      lapRecord: "1:16.627 (Hamilton, 2020)",
      trackSvg: tb + "hungaroringdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight", after: "T14" }],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Left",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Downhill Right",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Big Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Medium Right",
          speed: "125 km/h",
          gear: 3,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Fast Left",
          speed: "180 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Downhill Kink",
          speed: "210 km/h",
          gear: 6,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Uphill Entry",
          speed: "155 km/h",
          gear: 5,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Chicane Left",
          speed: "105 km/h",
          gear: 3,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Chicane Right",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Final Corner",
          speed: "165 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "zandvoort",
      name: "Circuit Zandvoort",
      location: "Zandvoort, Netherlands",
      flag: "nl",
      length: "4.259 km",
      laps: 72,
      firstGP: 1952,
      lapRecord: "1:11.097 (Hamilton, 2021)",
      trackSvg: tb + "zandvoortdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight", after: "T14" }],
      corners: [
        {
          num: 1,
          name: "Tarzanbocht",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Gerlachbocht",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Fast Kink",
          speed: "210 km/h",
          gear: 6,
        },
        {
          num: 7,
          name: "Scheivlak",
          type: "Blind Crest",
          speed: "235 km/h",
          gear: 7,
        },
        {
          num: 8,
          name: "Mastersbocht",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Hans Ernstbocht",
          type: "Medium Left",
          speed: "120 km/h",
          gear: 3,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Right",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 11,
          name: "Hugenholtz",
          type: "Banked Turn",
          speed: "215 km/h",
          gear: 6,
        },
        {
          num: 12,
          name: "Kumho",
          type: "Fast Left",
          speed: "180 km/h",
          gear: 5,
        },
        {
          num: 13,
          name: "Arie Luyendykbocht",
          type: "Medium Right",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Banked Final Turn",
          type: "Banked Corner",
          speed: "225 km/h",
          gear: 6,
        },
      ],
    },
    {
      id: "monza",
      name: "Autodromo Nazionale Monza",
      location: "Monza, Italy",
      flag: "it",
      length: "5.793 km",
      laps: 53,
      firstGP: 1950,
      lapRecord: "1:20.901 (Norris, 2025)",
      trackSvg: tb + "monzadetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "Parabolica" },
        { zone: 2, straight: "Back Straight", after: "Variante della Roggia" },
      ],
      corners: [
        {
          num: 1,
          name: "Variante del Rettifilo 1",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Variante del Rettifilo 2",
          type: "Chicane Exit",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Curva Grande",
          type: "Flat Out",
          speed: "320 km/h",
          gear: 8,
        },
        {
          num: 4,
          name: "Variante della Roggia 1",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 5,
          name: "Variante della Roggia 2",
          type: "Chicane Exit",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 6,
          name: "Lesmo 1",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Lesmo 2",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        { num: 8, name: "Ascari", type: "Chicane", speed: "175 km/h", gear: 5 },
        {
          num: 9,
          name: "Parabolica (Alboreto)",
          type: "Long Right",
          speed: "215 km/h",
          gear: 6,
        },
      ],
    },
    {
      id: "madrid",
      name: "Madrid Circuit",
      location: "Madrid, Spain",
      flag: "es",
      length: "TBC",
      laps: 0,
      firstGP: 2026,
      lapRecord: "New circuit",
      trackSvg: tb + "madriddetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "TBC", after: "TBC" }],
      corners: [
        {
          num: 1,
          name: "New Circuit",
          type: "Corner names TBC",
          speed: "TBC",
          gear: 0,
        },
      ],
    },
    {
      id: "baku",
      name: "Baku City Circuit",
      location: "Baku, Azerbaijan",
      flag: "az",
      length: "6.003 km",
      laps: 51,
      firstGP: 2016,
      lapRecord: "1:43.009 (Leclerc, 2019)",
      trackSvg: tb + "bakudetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T20" },
        { zone: 2, straight: "After Castle Section", after: "T8" },
      ],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Right",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Uphill Left",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Fast Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Castle (Icheri Sheher)",
          type: "Tight Left",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 8,
          name: "Castle Section",
          type: "Narrow Chicane",
          speed: "55 km/h",
          gear: 1,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Medium Right",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Inner City Hairpin",
          speed: "70 km/h",
          gear: 2,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Medium Left",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Fast Kink",
          speed: "235 km/h",
          gear: 6,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Medium Right",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 17,
          name: "Turn 17",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 18,
          name: "Turn 18",
          type: "Fast Right",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 19,
          name: "Turn 19",
          type: "Medium Left",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 20,
          name: "Turn 20",
          type: "Final Corner",
          speed: "145 km/h",
          gear: 4,
        },
      ],
    },
    {
      id: "marina-bay",
      name: "Marina Bay Street Circuit",
      location: "Singapore",
      flag: "sg",
      length: "4.940 km",
      laps: 62,
      firstGP: 2008,
      lapRecord: "1:33.808 (Hamilton, 2025)",
      trackSvg: tb + "singaporedetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight", after: "T23" }],
      corners: [
        {
          num: 1,
          name: "Sheares",
          type: "Heavy Braking",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 5,
          name: "Stamford",
          type: "Tight Left",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 7,
          name: "Raffles Blvd Hairpin",
          type: "Hairpin",
          speed: "60 km/h",
          gear: 2,
        },
        {
          num: 9,
          name: "War Memorial",
          type: "Fast Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 10,
          name: "Singapore Sling",
          type: "Chicane",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 13,
          name: "Esplanade Curve",
          type: "Fast Right",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Turn 14 Chicane",
          type: "Tight Chicane",
          speed: "70 km/h",
          gear: 2,
        },
        {
          num: 16,
          name: "Anderson Bridge",
          type: "Tight Left",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 17,
          name: "Turn 17",
          type: "Medium Right",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 19,
          name: "Empress Place",
          type: "Fast Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 23,
          name: "Last Corner",
          type: "Final Turn",
          speed: "105 km/h",
          gear: 3,
        },
      ],
    },
    {
      id: "austin",
      name: "Circuit of the Americas",
      location: "Austin, United States",
      flag: "us",
      length: "5.513 km",
      laps: 56,
      firstGP: 2012,
      lapRecord: "1:36.169 (Leclerc, 2019)",
      trackSvg: tb + "austindetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T20" },
        { zone: 2, straight: "Back Straight", after: "T11" },
      ],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Uphill Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Esses Entry",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Esses Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Esses Right",
          speed: "180 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Esses Left",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Esses Exit",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Fast Right",
          speed: "220 km/h",
          gear: 6,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Left",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 11,
          name: "Hairpin",
          type: "Heavy Braking",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Downhill Switchback",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Medium Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Fast Left",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 15,
          name: "Stadium Turn",
          type: "Medium Right",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Stadium Entry",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 17,
          name: "Turn 17",
          type: "Stadium Section",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 18,
          name: "Turn 18",
          type: "Stadium Exit",
          speed: "150 km/h",
          gear: 4,
        },
        {
          num: 19,
          name: "Turn 19",
          type: "Back Straight Kink",
          speed: "245 km/h",
          gear: 7,
        },
        {
          num: 20,
          name: "Final Hairpin",
          type: "Heavy Braking",
          speed: "70 km/h",
          gear: 2,
        },
      ],
    },
    {
      id: "mexico",
      name: "Aut\u00f3dromo Hermanos Rodr\u00edguez",
      location: "Mexico City, Mexico",
      flag: "mx",
      length: "4.304 km",
      laps: 71,
      firstGP: 1963,
      lapRecord: "1:17.774 (Bottas, 2021)",
      trackSvg: tb + "mexicocitydetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T17" },
        { zone: 2, straight: "Into Hairpin", after: "T4" },
      ],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Esses Left",
          speed: "155 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Esses Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Fast Right",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Horquilla",
          type: "Hairpin",
          speed: "60 km/h",
          gear: 2,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Esses Entry",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Esses Middle",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Esses Exit",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 12,
          name: "Baseball Diamond",
          type: "Peraltada Entry",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 13,
          name: "Foro Sol Entry",
          type: "Stadium Entry",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Stadium Section",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Stadium Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Stadium Exit",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 17,
          name: "Last Corner",
          type: "Final Turn",
          speed: "155 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "interlagos",
      name: "Aut\u00f3dromo Jos\u00e9 Carlos Pace",
      location: "S\u00e3o Paulo, Brazil",
      flag: "br",
      length: "4.309 km",
      laps: 71,
      firstGP: 1973,
      lapRecord: "1:10.540 (Bottas, 2018)",
      trackSvg: tb + "interlagosdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T14" },
        { zone: 2, straight: "Into Senna S", after: "Reta Oposta" },
      ],
      corners: [
        {
          num: 1,
          name: "Senna S (Entry)",
          type: "Heavy Braking",
          speed: "95 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Senna S (Exit)",
          type: "Chicane Exit",
          speed: "130 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Curva do Sol",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Descida do Lago",
          type: "Downhill Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Ferradura Entry",
          type: "Medium Left",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 7,
          name: "Ferradura Exit",
          type: "Fast Exit",
          speed: "155 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "Laranjinha",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 10,
          name: "Pinheirinho",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Fast Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 12,
          name: "Jun\u00e7\u00e3o",
          type: "Heavy Braking",
          speed: "75 km/h",
          gear: 2,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Medium Right",
          speed: "140 km/h",
          gear: 4,
        },
        {
          num: 14,
          name: "Subida dos Boxes",
          type: "Uphill Final",
          speed: "155 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "las-vegas",
      name: "Las Vegas Strip Circuit",
      location: "Las Vegas, United States",
      flag: "us",
      length: "6.201 km",
      laps: 50,
      firstGP: 2023,
      lapRecord: "1:33.365 (Verstappen, 2025)",
      trackSvg: tb + "lasvegasdetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Las Vegas Blvd (The Strip)", after: "T17" },
        { zone: 2, straight: "Koval Straight", after: "T6" },
      ],
      corners: [
        {
          num: 1,
          name: "MSS Chicane 1",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "MSS Chicane 2",
          type: "Chicane Exit",
          speed: "120 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Harmon Corner",
          type: "Medium Left",
          speed: "115 km/h",
          gear: 3,
        },
        {
          num: 5,
          name: "Koval Chicane 1",
          type: "Heavy Braking",
          speed: "80 km/h",
          gear: 2,
        },
        {
          num: 6,
          name: "Koval Chicane 2",
          type: "Chicane Exit",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Right",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Medium Left",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 10,
          name: "Sands Hairpin",
          type: "Hairpin",
          speed: "55 km/h",
          gear: 2,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 12,
          name: "Sphere Turn",
          type: "Medium Right",
          speed: "125 km/h",
          gear: 4,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Fast Left",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 14,
          name: "Las Vegas Blvd Turn",
          type: "Medium Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Fast Right",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 17,
          name: "Final Corner",
          type: "Medium Right",
          speed: "145 km/h",
          gear: 4,
        },
      ],
    },
    {
      id: "lusail",
      name: "Lusail International Circuit",
      location: "Lusail, Qatar",
      flag: "qa",
      length: "5.419 km",
      laps: 57,
      firstGP: 2021,
      lapRecord: "1:22.384 (Norris, 2024)",
      trackSvg: tb + "lusaildetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [{ zone: 1, straight: "Main Straight", after: "T16" }],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "85 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Right",
          speed: "165 km/h",
          gear: 5,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Esses Entry",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 5,
          name: "Turn 5",
          type: "Esses Exit",
          speed: "190 km/h",
          gear: 5,
        },
        {
          num: 6,
          name: "Turn 6",
          type: "Fast Left",
          speed: "225 km/h",
          gear: 6,
        },
        {
          num: 7,
          name: "Turn 7",
          type: "Switchback Right",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 9,
          name: "Turn 9",
          type: "Fast Right",
          speed: "205 km/h",
          gear: 6,
        },
        {
          num: 10,
          name: "Hairpin",
          type: "Heavy Braking",
          speed: "65 km/h",
          gear: 2,
        },
        {
          num: 11,
          name: "Turn 11",
          type: "Medium Right",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 12,
          name: "Turn 12",
          type: "Double Apex Entry",
          speed: "170 km/h",
          gear: 5,
        },
        {
          num: 13,
          name: "Turn 13",
          type: "Double Apex Exit",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 14,
          name: "Turn 14",
          type: "Fast Right",
          speed: "215 km/h",
          gear: 6,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Medium Left",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 16,
          name: "Turn 16",
          type: "Penultimate Corner",
          speed: "175 km/h",
          gear: 5,
        },
      ],
    },
    {
      id: "yas-marina",
      name: "Yas Marina Circuit",
      location: "Abu Dhabi, UAE",
      flag: "ae",
      length: "5.281 km",
      laps: 58,
      firstGP: 2009,
      lapRecord: "1:25.637 (Magnussen, 2024)",
      trackSvg: tb + "yasmarinadetailed.webp",
      sectors: [
        { name: "S1", color: "#e10600" },
        { name: "S2", color: "#ffd700" },
        { name: "S3", color: "#2196F3" },
      ],
      overtakeZones: [
        { zone: 1, straight: "Main Straight", after: "T16" },
        { zone: 2, straight: "Back Straight", after: "T9" },
      ],
      corners: [
        {
          num: 1,
          name: "Turn 1",
          type: "Heavy Braking",
          speed: "90 km/h",
          gear: 3,
        },
        {
          num: 2,
          name: "Turn 2",
          type: "Fast Left",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 3,
          name: "Turn 3",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 4,
          name: "Turn 4",
          type: "Medium Left",
          speed: "135 km/h",
          gear: 4,
        },
        {
          num: 5,
          name: "Hotel Hairpin",
          type: "Hairpin",
          speed: "62 km/h",
          gear: 2,
        },
        {
          num: 6,
          name: "North Esses 1",
          type: "Fast Left",
          speed: "195 km/h",
          gear: 5,
        },
        {
          num: 7,
          name: "North Esses 2",
          type: "Fast Right",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 8,
          name: "Turn 8",
          type: "Fast Left",
          speed: "210 km/h",
          gear: 6,
        },
        {
          num: 9,
          name: "Hotel Chicane",
          type: "Heavy Braking",
          speed: "78 km/h",
          gear: 2,
        },
        {
          num: 10,
          name: "Turn 10",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 11,
          name: "Marina Hairpin",
          type: "Hairpin",
          speed: "68 km/h",
          gear: 2,
        },
        {
          num: 12,
          name: "South Marina 1",
          type: "Fast Left",
          speed: "155 km/h",
          gear: 4,
        },
        {
          num: 13,
          name: "South Marina 2",
          type: "Fast Right",
          speed: "175 km/h",
          gear: 5,
        },
        {
          num: 14,
          name: "South Marina 3",
          type: "Fast Left",
          speed: "185 km/h",
          gear: 5,
        },
        {
          num: 15,
          name: "Turn 15",
          type: "Medium Right",
          speed: "145 km/h",
          gear: 4,
        },
        {
          num: 16,
          name: "Yas Chicane",
          type: "Final Chicane",
          speed: "105 km/h",
          gear: 3,
        },
      ],
    },
  ];

  var selectedCircuit = explorerCircuits[0];

  function renderExplorer() {
    var thumbsContainer = document.getElementById("circuit-thumbs");
    thumbsContainer.innerHTML = "";
    explorerCircuits.forEach(function (circuit) {
      var btn = document.createElement("button");
      btn.className =
        "circuit-thumb" +
        (selectedCircuit.id === circuit.id ? " circuit-thumb-active" : "");
      btn.innerHTML =
        '<img src="https://flagcdn.com/w40/' +
        circuit.flag +
        '.png" alt="' +
        circuit.location +
        '" class="thumb-flag"><span class="thumb-name">' +
        circuit.location.split(",")[0] +
        "</span>";
      btn.addEventListener("click", function () {
        selectedCircuit = circuit;
        renderExplorer();
      });
      thumbsContainer.appendChild(btn);
    });

    document.getElementById("map-flag").src =
      "https://flagcdn.com/w40/" + selectedCircuit.flag + ".png";
    document.getElementById("map-circuit-name").textContent =
      selectedCircuit.name;
    document.getElementById("map-circuit-location").textContent =
      selectedCircuit.location;
    document.getElementById("map-length").textContent = selectedCircuit.length;
    document.getElementById("map-laps").textContent =
      selectedCircuit.laps || "TBC";
    document.getElementById("map-corners").textContent =
      selectedCircuit.corners.length;

    document.getElementById("track-svg-bg").src = selectedCircuit.trackSvg;
    document.getElementById("track-svg-bg").alt = selectedCircuit.name;

    document.getElementById("legend-sectors").innerHTML =
      selectedCircuit.sectors
        .map(function (s) {
          return (
            '<div class="legend-item"><span class="legend-color" style="background:' +
            s.color +
            '"></span><span>' +
            s.name +
            "</span></div>"
          );
        })
        .join("");

    document.getElementById("legend-overtake").innerHTML =
      selectedCircuit.overtakeZones
        .map(function (o) {
          return (
            '<div class="legend-item"><span class="legend-overtake-badge">OT ' +
            o.zone +
            "</span><span>" +
            o.straight +
            "</span></div>"
          );
        })
        .join("");

    var cornerList = document.getElementById("corner-list");
    cornerList.innerHTML = "";
    selectedCircuit.corners.forEach(function (corner) {
      var item = document.createElement("div");
      item.className = "corner-list-item";
      item.innerHTML =
        '<div class="corner-list-left">' +
        '<span class="corner-list-num">' +
        corner.num +
        "</span>" +
        '<div class="corner-list-info">' +
        '<span class="corner-list-name">' +
        corner.name +
        "</span>" +
        '<span class="corner-list-type">' +
        corner.type +
        "</span>" +
        "</div>" +
        "</div>" +
        '<div class="corner-list-right">' +
        '<span class="corner-list-speed">' +
        corner.speed +
        "</span>" +
        (corner.gear
          ? '<span class="corner-list-gear">G' + corner.gear + "</span>"
          : "") +
        (corner.overtake
          ? '<span class="corner-list-overtake">OVERTAKE</span>'
          : "") +
        "</div>";
      cornerList.appendChild(item);
    });
  }

  renderExplorer();
});
